### PR TITLE
MRG: update latest figures + add data

### PR DESCRIPTION
**Pull request by dengemann**
Hi @KamalakerDadi here we go. This brings the latest figures + the intermediate computation and data needed to play with the results. Let's have a careful look before merging.

### CODE REVIEW

**Comment by dengemann** [comment]
OK, it seems the data files I'm trying to add are too large for GitHub. I'll try to find a workaround.

**Comment by KamalakerDadi** [comment]
Thanks for the PR. Please let me know when to review.

**Comment by KamalakerDadi** [comment]
@dengemann What is the idea? Would you like to make the scripts runnable?

**Comment by dengemann** [comment]
Hi Kamalakar, the diff is too large unfortunately, but perhaps you can pull and look on your computer or check out my fork https://github.com/dengemann/proxy_measures_2020/tree/curated_viz

**Comment by KamalakerDadi** [comment]
Great work. Thank you!

**Pull request merged**
